/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mapaprogii;

import java.util.ArrayList;
import java.util.List;
import java.util.Iterator;

/**
 *
 * @author Breno
 */
public class InterfaceG extends javax.swing.JFrame {
    List<Senha> listadeSenhas;
    int i = 0;
    int y = 0;
    
    public InterfaceG() {
        initComponents();
        listadeSenhas = new ArrayList();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        saidaSenha = new javax.swing.JLabel();
        imprimeCaixa = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        caixaUM = new javax.swing.JButton();
        caixaTres = new javax.swing.JButton();
        caixaQuatro = new javax.swing.JButton();
        caixaDois = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnRapido = new javax.swing.JButton();
        btnComum = new javax.swing.JButton();
        btnPrioridade = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        entradaSenha = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        saidaSenha.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        saidaSenha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        saidaSenha.setText("Aguarde...");

        imprimeCaixa.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        imprimeCaixa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imprimeCaixa.setText("-");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Funcionário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 14))); // NOI18N

        caixaUM.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        caixaUM.setText("Caixa 1");
        caixaUM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaUMActionPerformed(evt);
            }
        });

        caixaTres.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        caixaTres.setText("Caixa 3");
        caixaTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaTresActionPerformed(evt);
            }
        });

        caixaQuatro.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        caixaQuatro.setText("Caixa 4");
        caixaQuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaQuatroActionPerformed(evt);
            }
        });

        caixaDois.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        caixaDois.setText("Caixa 2");
        caixaDois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaDoisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(caixaUM)
                    .addComponent(caixaDois))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(caixaTres)
                    .addComponent(caixaQuatro))
                .addGap(52, 52, 52))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caixaUM)
                    .addComponent(caixaTres))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caixaQuatro)
                    .addComponent(caixaDois))
                .addGap(19, 19, 19))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 14))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setText("Escolha seu tipo de atendimento:");

        btnRapido.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnRapido.setText("Rápido");
        btnRapido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRapidoActionPerformed(evt);
            }
        });

        btnComum.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnComum.setText("Comum");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, entradaSenha, org.jdesktop.beansbinding.ELProperty.create("Olá Mundo"), btnComum, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        btnComum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComumActionPerformed(evt);
            }
        });

        btnPrioridade.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnPrioridade.setText("Prioritário");
        btnPrioridade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrioridadeActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel4.setText("Sua senha é:");

        entradaSenha.setEditable(false);
        entradaSenha.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        entradaSenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        entradaSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaSenhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnComum)
                        .addGap(43, 43, 43)
                        .addComponent(btnRapido)
                        .addGap(39, 39, 39)
                        .addComponent(btnPrioridade))
                    .addComponent(jLabel3)
                    .addComponent(entradaSenha))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnComum)
                    .addComponent(btnRapido)
                    .addComponent(btnPrioridade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(1, 1, 1)
                .addComponent(entradaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(337, 337, 337)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imprimeCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saidaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(81, 81, 81)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(saidaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(imprimeCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComumActionPerformed
       Senha comum = new Senha();
       
       i++;
       comum.setTipo("C");
       comum.setNum(i);
       
       listadeSenhas.add(comum);
       entradaSenha.setText(comum.toString());
    }//GEN-LAST:event_btnComumActionPerformed

    private void entradaSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaSenhaActionPerformed

    private void btnRapidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRapidoActionPerformed
       Senha rapido = new Senha();
        
       i++;
       rapido.setTipo("R");
       rapido.setNum(i);

       listadeSenhas.add(rapido);
       entradaSenha.setText(rapido.toString());
    }//GEN-LAST:event_btnRapidoActionPerformed

    private void btnPrioridadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrioridadeActionPerformed
       Senha prioridade = new Senha();
        
       i++;
       prioridade.setTipo("P");
       prioridade.setNum(i);

       listadeSenhas.add(prioridade);
       entradaSenha.setText(prioridade.toString());
    }//GEN-LAST:event_btnPrioridadeActionPerformed

    private void caixaUMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaUMActionPerformed

        try{
        
            Iterator<Senha> itr = listadeSenhas.iterator();
            boolean cxAberto = false;
        
            while (itr.hasNext()) {
                Senha s = itr.next();

                if (s.tipo.equals("P")) {
                    listadeSenhas.remove(s);
                    saidaSenha.setText(s.toString());
                    imprimeCaixa.setText("Caixa1");
                    cxAberto = true;
                    break;
                }
        }
            if (!cxAberto == true) {
                Senha s = listadeSenhas.get(0);
                saidaSenha.setText(s.toString());
                listadeSenhas.remove(0);
            }
        }catch(Exception e) {
            e.getMessage();
        }
    }//GEN-LAST:event_caixaUMActionPerformed

    private void caixaDoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaDoisActionPerformed
        
        try {
        
            Iterator<Senha> itr = listadeSenhas.iterator();
            boolean cxAberto = false;
            
            while (itr.hasNext()) {
                Senha s = itr.next();
                
                if(s.tipo.equals("R")) {
                    listadeSenhas.remove(s);
                    saidaSenha.setText(s.toString());
                    imprimeCaixa.setText("Caixa2");
                    cxAberto = true;
                    break;
                }
        }
        
            if (!cxAberto == true) {
                Senha s = listadeSenhas.get(0);
                saidaSenha.setText(s.toString());
                imprimeCaixa.setText("Caixa2");
                listadeSenhas.remove(0);
            }
    }catch(Exception e) {
        e.getMessage();
    }
        
    }//GEN-LAST:event_caixaDoisActionPerformed

    private void caixaTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaTresActionPerformed
        
        try {
            Iterator<Senha> itr = listadeSenhas.iterator();
            boolean cxAberto = false;

            while (itr.hasNext()) {
                Senha s = itr.next();
                
                if(s.tipo.equals("R")) {
                    listadeSenhas.remove(s);
                    saidaSenha.setText(s.toString());
                    imprimeCaixa.setText("Caixa3");
                    cxAberto = true;
                    break;
                } 
            }

            if(!cxAberto == true){
                Senha s = listadeSenhas.get(0);
                saidaSenha.setText(s.toString());
                imprimeCaixa.setText("Caixa3");
                listadeSenhas.remove(0);
            }
        }catch(Exception e) {
            e.getMessage();
        }
        
    }//GEN-LAST:event_caixaTresActionPerformed

    private void caixaQuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaQuatroActionPerformed
        try {
            Iterator<Senha> itr = listadeSenhas.iterator();
            boolean cxAberto = false;
        
            while (itr.hasNext()) {
                Senha s = itr.next();

                if(s.tipo.equals("C")) {
                    listadeSenhas.remove(s);
                    saidaSenha.setText(s.toString());
                    imprimeCaixa.setText("Caixa4");
                    cxAberto = true;
                    break;
                }
            }
            if(!cxAberto == true) {
                Senha s = listadeSenhas.get(0);
                saidaSenha.setText(s.toString());
                imprimeCaixa.setText("Caixa4");
                listadeSenhas.remove(0);
            }
        }catch (Exception e) {
            e.getMessage();
        }
    }//GEN-LAST:event_caixaQuatroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceG().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComum;
    private javax.swing.JButton btnPrioridade;
    private javax.swing.JButton btnRapido;
    private javax.swing.JButton caixaDois;
    private javax.swing.JButton caixaQuatro;
    private javax.swing.JButton caixaTres;
    private javax.swing.JButton caixaUM;
    private javax.swing.JTextField entradaSenha;
    private javax.swing.JLabel imprimeCaixa;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel saidaSenha;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
